### GET EMBEDLY DATA FOR URLS

GET https://api-cdn.embed.ly/1/card-details?card=1&native=true&scheme=https&urls={{urls}}&key={{embedlyApi}} HTTP/1.1
Connection: keep-alive
Accept-Encoding: identity;q=1, *;q=0
chrome-proxy: frfr
Referer: http://alesund-dev.intra.work/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Language: nb,en-US;q=0.9,en;q=0.8,es;q=0.7
