export enum Types {
    SET_API_ENDPOINT = "SET_API_ENDPOINT",
	SET_ACCESS_TOKEN_OVERRIDE = "SET_ACCESS_TOKEN_OVERRIDE",
	SET_LANGUAGE = "SET_LANGUAGE",
	SET_AUTORIZATION_DATA = "SET_AUTORIZATION_DATA",
	SET_PROFILE = "SET_PROFILE",
	SET_SIGNED_IN = "SET_SIGNED_IN",
	SET_CONTACTS = "SET_CONTACTS",
	UPDATE_CONTACT = "UPDATE_CONTACT",
	SET_COMMUNITIES = "SET_COMMUNITIES",
	UPDATE_COMMUNITY = "UPDATE_COMMUNITY"
}